name: Process Text Files

on:
  push:
    branches:
      - main  # Setze hier den Branch ein, auf den die Action reagieren soll

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run processing script
      run: python scripts/process_files.py

    - name: Upload SQL file
      uses: actions/upload-artifact@v3
      with:
        name: sql-file
        path: output.sql
